backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/img
public_folder: "/img"
collections:
- name: pages
  label: Pages
  label_singular: Page
  folder: docs
  path: '{{path}}'
  create: true
  nested:
    depth: 100
    summary: '{{title}}'
  meta:
    path:
      widget: string
      label: Path
      index_file: index
  fields:
  - label: Title
    name: title
    widget: string
  - label: Path
    name: path
    widget: path
  - label: Sidebar Label
    name: sidebar_label
    widget: string
    optional: true
  - label: Body
    name: body
    widget: markdown
  