backend:
    name: git-gateway
    branch: master

media_folder: static/img
public_folder: /img

collections:
    - name: "content"
      label: "Content"
      folder: "docs"
      create: true
    #   slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}        
        - {label: "Category", name: "category", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  